import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import Calendar from "@/components/calendar/Calendar";
import { Toaster } from "@/components/ui/toaster";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className="">
				<Provider>
					<main className="">
						<Navbar />
						{children}
					</main>
					<Toaster />
				</Provider>
			</body>
		</html>
	);
}
